logging:
  level:
    org:
      springframework: DEBUG
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1434;database=goose;
    user: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
 #       id:
 #         new_generator_mappings: true
        format_sql: true
    show-sql: true
server:
  port: 8080

